node('docker02.woodez.net') {
   def commit_id
   stage('Preperation') {
     checkout scm
     sh "git rev-parse --short HEAD > .git/commit-id"
     commit_id = readFile('.git/commit-id').trim()
     env_id = 'dev'
   }

   stage('docker build/push') {
     docker.withRegistry('https://index.docker.io/v1/', 'dockerhub') {
       def app = docker.build("kwood475/baseball:${env_id}", '.').push()
     }
   }

#  stage('docker stop container') {
#     sh 'docker container rm -f baseball'
#  }
   stage('docker run container') {
     def apiContainer = docker.image("kwood475/baseball:${env_id}").run("--name baseball --publish 4000:4000")
   }
}